FROM golang:1.24 AS builder

WORKDIR /app-1

COPY go.mod go.sum ./
RUN go mod download

COPY main.go ./
RUN GOOS=linux go build -o main .

FROM alpine:latest

COPY --from=builder /app-1/main .
EXPOSE 8080
CMD ["sh", "-c", "ls -al /main && pwd && file /main"]
