services:
  api-gateway:
    build:
      context: api_gateway/
      dockerfile: Dockerfile.gateway
    ports:
      - "8083:8083"
    networks:
      - backend
    env_file: ./api_gateway/.env

  backend-service:
    build:
      context: test_backend/
      dockerfile: Dockerfile.backend
    ports:
      - "8081:8081"
    networks:
      - backend
    env_file: ./test_backend/.env

  ping-service:
    build:
      context: ping_service/
      dockerfile: Dockerfile.backend
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge
