services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    networks:
      - backend

  backend-service:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge
