FROM golang:1.18-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY backend.go ./
RUN GOOS=linux GOARCH=arm64 go build -o backend .

FROM alpine:latest

COPY --from=builder /app/backend .
EXPOSE 8081
CMD ["./backend"]
