FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY main.go ./
RUN GOOS=linux go build -o main .

FROM alpine:latest

COPY --from=builder /app/main .
EXPOSE 8083
CMD ["./main"]
