FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY backend.go ./
RUN GOOS=linux go build -o ping .

FROM alpine:latest

COPY --from=builder /app/ping .
EXPOSE 8082
CMD ["./ping"]
