FROM golang:1.24 AS builder

WORKDIR /app-2

COPY go.mod go.sum ./
RUN go mod download

COPY backend.go ./
RUN GOOS=linux go build -o backend .

FROM alpine:latest

COPY --from=builder /app-2/backend .
EXPOSE 8081
CMD ["sh", "-c", "ls -al /backend && pwd && file /backend"]
